//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electroplus_Media_Converter.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Electroplus_Media_Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }











        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports scope of access violated..
        /// </summary>
        internal static string AccessViolatedTxt
        {
            get
            {
                return ResourceManager.GetString("AccessViolatedTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Data Block Number Invalid..
        /// </summary>
        internal static string DataBlockNumberInvalidTxt
        {
            get
            {
                return ResourceManager.GetString("DataBlockNumberInvalidTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Data Block Unavailable..
        /// </summary>
        internal static string DataBlockUnavailableTxt
        {
            get
            {
                return ResourceManager.GetString("DataBlockUnavailableTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect mode..
        /// </summary>
        internal static string DisconnectMode
        {
            get
            {
                return ResourceManager.GetString("DisconnectMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a hardware fault..
        /// </summary>
        internal static string HardwareFaultTxt
        {
            get
            {
                return ResourceManager.GetString("HardwareFaultTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a inconsistent Class or object..
        /// </summary>
        internal static string InconsistentClassTxt
        {
            get
            {
                return ResourceManager.GetString("InconsistentClassTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1;0.0.94.91.9.255;0;Meter type
        ///1;0.0.94.91.11.255;0;Category
        ///1;0.0.94.91.12.255;0;Current rating 
        ///1;0.0.96.1.4.255;0;0;Meter year of manufacture
        ///1;0.0.94.91.18.255;0;Event Status word 1 (ESW 1)
        ///1;0.0.94.91.0.255;0;Cumulative tamper count
        ///3;0.0.94.91.13.255;0;Cumulative power ON duration in minutes
        ///3;1.0.94.91.14.255;0;Current
        ///3;0.0.94.91.8.255;0;Cumulative power — OFF duration in min
        ///7;1.0.94.91.0.255;0;Snapshot of Instantaneous Parameters
        ///7;1.0.94.91.7.255;0;Scaler Profile
        ///7;1.0.94.91.3.255;0;Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string India
        {
            get
            {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Logical name..
        /// </summary>
        internal static string InvalidLogicalName
        {
            get
            {
                return ResourceManager.GetString("InvalidLogicalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1;0.0.96.1.0.255;0;Manufacturing number
        ///1;0.0.96.1.10.255;0;Metering Point Identifier
        ///1;0.0.96.1.3.255;0;Equipment Class Identifier
        ///1;0.0.96.1.5.255;0;UNI/TS Reference version
        ///17;0.0.41.0.0.255;0;SAP assigment
        ///1;0.0.42.0.0.255;0;Logical Device Name
        ///15;0.0.40.0.1.255;2;Management Association
        ///15;0.0.40.0.16.255;2;Public Association
        ///15;0.0.40.0.3.255;2;Installer/Maintainer Association
        ///15;0.0.40.0.48.255;2;Guarantor Authority Association
        ///15;0.0.40.0.64.255;2;Gateway Association
        ///15;0.0.40.0.32.255;2;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Italy
        {
            get
            {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logical Name.
        /// </summary>
        internal static string LogicalNameTxt
        {
            get
            {
                return ResourceManager.GetString("LogicalNameTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Long Get Or Read Aborted..
        /// </summary>
        internal static string LongGetOrReadAbortedTxt
        {
            get
            {
                return ResourceManager.GetString("LongGetOrReadAbortedTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Long Set Or Write Aborted..
        /// </summary>
        internal static string LongSetOrWriteAbortedTxt
        {
            get
            {
                return ResourceManager.GetString("LongSetOrWriteAbortedTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : No Long Get Or Read In Progress..
        /// </summary>
        internal static string NoLongGetOrReadInProgressTxt
        {
            get
            {
                return ResourceManager.GetString("NoLongGetOrReadInProgressTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : No Long Set Or Write In Progress..
        /// </summary>
        internal static string NoLongSetOrWriteInProgressTxt
        {
            get
            {
                return ResourceManager.GetString("NoLongSetOrWriteInProgressTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.0-64.0.1.0.0-99,255;1,3,4;6,17,18;Ch. $B;Billing period counter (1);;;#$F
        ///0.0-64.0.1.1.255;1,3,4;6,17,18;Ch. $B;No. of available billing periods (1);;;
        ///0.0-64.0.1.2.0-99;1,3,4;9,25;Ch. $B;Time stamp of the billing period (1);;;#$F
        ///0.0-64.0.1.2.255;1,3,4;9,25;Ch. $B;Time stamp of the most recent billing period (1) closed;;;
        ///0.0-64.0.1.3.0-99,255;1,3,4;6,17,18;Ch. $B;Billing period counter (2), VZ;;;#$F
        ///0.0-64.0.1.4.255;1,3,4;6,17,18;Ch. $B;No. of available billing periods (2);;;
        ///0.0-64.0.1.5.0-99;1,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OBISCodes
        {
            get
            {
                return ResourceManager.GetString("OBISCodes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Other Reason..
        /// </summary>
        internal static string OtherReasonTxt
        {
            get
            {
                return ResourceManager.GetString("OtherReasonTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports Read-Write denied..
        /// </summary>
        internal static string ReadWriteDeniedTxt
        {
            get
            {
                return ResourceManager.GetString("ReadWriteDeniedTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HDLC message rejected..
        /// </summary>
        internal static string Rejected
        {
            get
            {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1;0.1.94.96.2.255;0;Storage Device Failure Date/Time
        ///1;0.1.94.96.22.255;0;LCD time-to-return to default screen
        ///1;0.1.94.96.23.255;0;LCD auto scroll time
        ///1;0.1.94.96.24.255;0;LCD night off option
        ///1;0.1.94.96.25.255;0;Start-stop time setting of LCD night off
        ///9;0.1.94.96.10.255;0;Meter Program Configuration
        ///9;0.1.94.96.11.255;0;Meter Program Configuration Status
        ///1;0.96.94.96.8.255;0;Remote output relay control Selection of the input control signals
        ///1;0.96.94.96.9.255;0;Auto recovery operation times of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaudiArabia
        {
            get
            {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }

        internal static string Spain
        {
            get
            {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a temporary failure..
        /// </summary>
        internal static string TemporaryFailureTxt
        {
            get
            {
                return ResourceManager.GetString("TemporaryFailureTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unacceptable frame..
        /// </summary>
        internal static string UnacceptableFrame
        {
            get
            {
                return ResourceManager.GetString("UnacceptableFrame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unavailable object..
        /// </summary>
        internal static string UnavailableObjectTxt
        {
            get
            {
                return ResourceManager.GetString("UnavailableObjectTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a undefined object..
        /// </summary>
        internal static string UndefinedObjectTxt
        {
            get
            {
                return ResourceManager.GetString("UndefinedObjectTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A260*60s.
        /// </summary>
        internal static string UnitA260Txt
        {
            get
            {
                return ResourceManager.GetString("UnitA260Txt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active energy W*60*60s.
        /// </summary>
        internal static string UnitActiveEnergyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitActiveEnergyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active power P watt W = J/s.
        /// </summary>
        internal static string UnitActivePowerTxt
        {
            get
            {
                return ResourceManager.GetString("UnitActivePowerTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active energy meter constant 1/Wh.
        /// </summary>
        internal static string UnitActiveTxt
        {
            get
            {
                return ResourceManager.GetString("UnitActiveTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apparent energy VA*60*60s.
        /// </summary>
        internal static string UnitApparentEnergyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitApparentEnergyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apparent power S.
        /// </summary>
        internal static string UnitApparentPowerTxt
        {
            get
            {
                return ResourceManager.GetString("UnitApparentPowerTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apparent energy meter constant.
        /// </summary>
        internal static string UnitApparentTxt
        {
            get
            {
                return ResourceManager.GetString("UnitApparentTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capacity C farad C/V = As/V.
        /// </summary>
        internal static string UnitCapacityTxt
        {
            get
            {
                return ResourceManager.GetString("UnitCapacityTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conductance siemens 1/ohm.
        /// </summary>
        internal static string UnitConductanceTxt
        {
            get
            {
                return ResourceManager.GetString("UnitConductanceTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Corrected volume flux m3/60*60s.
        /// </summary>
        internal static string UnitCorrectedVolumeFluxHourTxt
        {
            get
            {
                return ResourceManager.GetString("UnitCorrectedVolumeFluxHourTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Corrected volume m3.
        /// </summary>
        internal static string UnitCorrectedVolumeTxt
        {
            get
            {
                return ResourceManager.GetString("UnitCorrectedVolumeTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Corrected volume flux m3/24*60*60s.
        /// </summary>
        internal static string UnitCorrecteVolumeFluxDayTxt
        {
            get
            {
                return ResourceManager.GetString("UnitCorrecteVolumeFluxDayTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current I ampere A.
        /// </summary>
        internal static string UnitCurrentTxt
        {
            get
            {
                return ResourceManager.GetString("UnitCurrentTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string UnitDayTxt
        {
            get
            {
                return ResourceManager.GetString("UnitDayTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Electrical charge Q coulomb C = As.
        /// </summary>
        internal static string UnitElectricalChargeTxt
        {
            get
            {
                return ResourceManager.GetString("UnitElectricalChargeTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Electrical field strength E V/m.
        /// </summary>
        internal static string UnitElectricalFieldStrengthTxt
        {
            get
            {
                return ResourceManager.GetString("UnitElectricalFieldStrengthTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Energy joule J = Nm = Ws.
        /// </summary>
        internal static string UnitEnergyJouleTxt
        {
            get
            {
                return ResourceManager.GetString("UnitEnergyJouleTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Energy newtonmeter J = Nm = Ws.
        /// </summary>
        internal static string UnitEnergyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitEnergyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force F newton N.
        /// </summary>
        internal static string UnitForceTxt
        {
            get
            {
                return ResourceManager.GetString("UnitForceTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frequency f.
        /// </summary>
        internal static string UnitFrequencyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitFrequencyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string UnitHourTxt
        {
            get
            {
                return ResourceManager.GetString("UnitHourTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Induction T tesla Wb/m2.
        /// </summary>
        internal static string UnitInductionTxt
        {
            get
            {
                return ResourceManager.GetString("UnitInductionTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inductivity L henry H = Wb/A.
        /// </summary>
        internal static string UnitInductivityTxt
        {
            get
            {
                return ResourceManager.GetString("UnitInductivityTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Length l meter m.
        /// </summary>
        internal static string UnitLengthTxt
        {
            get
            {
                return ResourceManager.GetString("UnitLengthTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local currency.
        /// </summary>
        internal static string UnitLocalCurrencyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitLocalCurrencyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magnetic flux F weber Wb = Vs.
        /// </summary>
        internal static string UnitMagneticFluxTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMagneticFluxTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magnetic field strength H A/m.
        /// </summary>
        internal static string UnitMagneticTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMagneticTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mass flux kg/s.
        /// </summary>
        internal static string UnitMassKgPerSecondTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMassKgPerSecondTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mass m kilogram kg.
        /// </summary>
        internal static string UnitMassKgTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMassKgTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string UnitMinuteTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMinuteTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string UnitMonthTxt
        {
            get
            {
                return ResourceManager.GetString("UnitMonthTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Unit.
        /// </summary>
        internal static string UnitNoneTxt
        {
            get
            {
                return ResourceManager.GetString("UnitNoneTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Unit.
        /// </summary>
        internal static string UnitOtherTxt
        {
            get
            {
                return ResourceManager.GetString("UnitOtherTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phase angle degree rad*180/p.
        /// </summary>
        internal static string UnitPhasAngleDegreeTxt
        {
            get
            {
                return ResourceManager.GetString("UnitPhasAngleDegreeTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pressure p bar 10-5 N/m2.
        /// </summary>
        internal static string UnitPressureBarTxt
        {
            get
            {
                return ResourceManager.GetString("UnitPressureBarTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pressure p pascal N/m2.
        /// </summary>
        internal static string UnitPressurePascalTxt
        {
            get
            {
                return ResourceManager.GetString("UnitPressurePascalTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reactive energy var*60*60s.
        /// </summary>
        internal static string UnitReactiveEnergyTxt
        {
            get
            {
                return ResourceManager.GetString("UnitReactiveEnergyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reactive power Q.
        /// </summary>
        internal static string UnitReactivePowerTxt
        {
            get
            {
                return ResourceManager.GetString("UnitReactivePowerTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reactive energy meter constant.
        /// </summary>
        internal static string UnitReactiveTxt
        {
            get
            {
                return ResourceManager.GetString("UnitReactiveTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resistance R ohm = V/A.
        /// </summary>
        internal static string UnitResistanceTxt
        {
            get
            {
                return ResourceManager.GetString("UnitResistanceTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resistivity.
        /// </summary>
        internal static string UnitResistivityTxt
        {
            get
            {
                return ResourceManager.GetString("UnitResistivityTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string UnitSecondTxt
        {
            get
            {
                return ResourceManager.GetString("UnitSecondTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speed v m/s.
        /// </summary>
        internal static string UnitSpeedTxt
        {
            get
            {
                return ResourceManager.GetString("UnitSpeedTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temperature T degree centigrade.
        /// </summary>
        internal static string UnitTemperatureTxt
        {
            get
            {
                return ResourceManager.GetString("UnitTemperatureTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thermal power J/60*60s.
        /// </summary>
        internal static string UnitThermalPowerTxt
        {
            get
            {
                return ResourceManager.GetString("UnitThermalPowerTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to V260*60s.
        /// </summary>
        internal static string UnitV260Txt
        {
            get
            {
                return ResourceManager.GetString("UnitV260Txt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string UnitVoltageTxt
        {
            get
            {
                return ResourceManager.GetString("UnitVoltageTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume V m3.
        /// </summary>
        internal static string UnitVolumeCubicMeterTxt
        {
            get
            {
                return ResourceManager.GetString("UnitVolumeCubicMeterTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume flux m3/24*60*60s.
        /// </summary>
        internal static string UnitVolumeFluxDayTxt
        {
            get
            {
                return ResourceManager.GetString("UnitVolumeFluxDayTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume flux m3/60*60s.
        /// </summary>
        internal static string UnitVolumeFluxHourTxt
        {
            get
            {
                return ResourceManager.GetString("UnitVolumeFluxHourTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume 10-3 m3.
        /// </summary>
        internal static string UnitVolumeLiterTxt
        {
            get
            {
                return ResourceManager.GetString("UnitVolumeLiterTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string UnitWeekTxt
        {
            get
            {
                return ResourceManager.GetString("UnitWeekTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string UnitYearTxt
        {
            get
            {
                return ResourceManager.GetString("UnitYearTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownErrorTxt
        {
            get
            {
                return ResourceManager.GetString("UnknownErrorTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unmatched type..
        /// </summary>
        internal static string UnmatchedTypeTxt
        {
            get
            {
                return ResourceManager.GetString("UnmatchedTypeTxt", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Attach by string can be used only with TCP/IP connection..
        /// </summary>
        internal static string AttachByStringCanBeUsedOnlyWithTCPIPConnection
        {
            get
            {
                return ResourceManager.GetString("AttachByStringCanBeUsedOnlyWithTCPIPConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client Settings:.
        /// </summary>
        internal static string ClientSettings
        {
            get
            {
                return ResourceManager.GetString("ClientSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string ClientTxt
        {
            get
            {
                return ResourceManager.GetString("ClientTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string HostNameTxt
        {
            get
            {
                return ResourceManager.GetString("HostNameTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid client..
        /// </summary>
        internal static string InvalidClient
        {
            get
            {
                return ResourceManager.GetString("InvalidClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid connection..
        /// </summary>
        internal static string InvalidConnection
        {
            get
            {
                return ResourceManager.GetString("InvalidConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid host name..
        /// </summary>
        internal static string InvalidHostName
        {
            get
            {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid port name..
        /// </summary>
        internal static string InvalidPortName
        {
            get
            {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid sender info..
        /// </summary>
        internal static string InvalidSenderInfo
        {
            get
            {
                return ResourceManager.GetString("InvalidSenderInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        internal static string IPv6Txt
        {
            get
            {
                return ResourceManager.GetString("IPv6Txt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string PortTxt
        {
            get
            {
                return ResourceManager.GetString("PortTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string ProtocolTxt
        {
            get
            {
                return ResourceManager.GetString("ProtocolTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Settings:.
        /// </summary>
        internal static string ServerSettings
        {
            get
            {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ServerTxt
        {
            get
            {
                return ResourceManager.GetString("ServerTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        internal static string SettingsTxt
        {
            get
            {
                return ResourceManager.GetString("SettingsTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown address..
        /// </summary>
        internal static string UnknownAddress
        {
            get
            {
                return ResourceManager.GetString("UnknownAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use IPv6.
        /// </summary>
        internal static string UseIPv6Txt
        {
            get
            {
                return ResourceManager.GetString("UseIPv6Txt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Cancel.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }






        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available
        {
            get
            {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available AddIns.
        /// </summary>
        internal static string AvailableAddIns
        {
            get
            {
                return ResourceManager.GetString("AvailableAddIns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available:.
        /// </summary>
        internal static string AvailableTxt
        {
            get
            {
                return ResourceManager.GetString("AvailableTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Updates.
        /// </summary>
        internal static string AvailableUpdatesTxt
        {
            get
            {
                return ResourceManager.GetString("AvailableUpdatesTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string CancelHelp
        {
            get
            {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string ClosesTheDialogBoxWithoutSavingAnyChangesYouHaveMade
        {
            get
            {
                return ResourceManager.GetString("ClosesTheDialogBoxWithoutSavingAnyChangesYouHaveMade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyTxt
        {
            get
            {
                return ResourceManager.GetString("CopyTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable
        {
            get
            {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled
        {
            get
            {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download
        {
            get
            {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable
        {
            get
            {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finding protocols..
        /// </summary>
        internal static string FindingProtocols
        {
            get
            {
                return ResourceManager.GetString("FindingProtocols", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable
        {
            get
            {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed:.
        /// </summary>
        internal static string Installed
        {
            get
            {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        internal static string InUse
        {
            get
            {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copies files to the clipboard..
        /// </summary>
        internal static string LibraryCopyHelp
        {
            get
            {
                return ResourceManager.GetString("LibraryCopyHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shows product and library versions..
        /// </summary>
        internal static string LibraryListHelp
        {
            get
            {
                return ResourceManager.GetString("LibraryListHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library Versions.
        /// </summary>
        internal static string LibraryVersionsTxt
        {
            get
            {
                return ResourceManager.GetString("LibraryVersionsTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationTxt
        {
            get
            {
                return ResourceManager.GetString("LocationTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameTxt
        {
            get
            {
                return ResourceManager.GetString("NameTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 3.5.
        /// </summary>
        internal static string NETFramework35
        {
            get
            {
                return ResourceManager.GetString("NETFramework35", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .Net framework 3.5 SP1 must be installed before the application can be used..
        /// </summary>
        internal static string NetFramework35SP1MustBeInstalledBeforeTheApplicationCanBeUsed
        {
            get
            {
                return ResourceManager.GetString("NetFramework35SP1MustBeInstalledBeforeTheApplicationCanBeUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .Net framework 3.5 SP1 or 4.0 must be installed before the application can be used..
        /// </summary>
        internal static string NetFramework35SP1Or40MustBeInstalledBeforeTheApplicationCanBeUsed
        {
            get
            {
                return ResourceManager.GetString("NetFramework35SP1Or40MustBeInstalledBeforeTheApplicationCanBeUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.0.
        /// </summary>
        internal static string NETFramework40
        {
            get
            {
                return ResourceManager.GetString("NETFramework40", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New updates available.
        /// </summary>
        internal static string NewProtocolsAvailableTxt
        {
            get
            {
                return ResourceManager.GetString("NewProtocolsAvailableTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There are new updates available. Do you want to download them?.
        /// </summary>
        internal static string NewProtocolsDownloadTxt
        {
            get
            {
                return ResourceManager.GetString("NewProtocolsDownloadTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not hex string.
        /// </summary>
        internal static string NotHexString
        {
            get
            {
                return ResourceManager.GetString("NotHexString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        internal static string ProtocolsTxt
        {
            get
            {
                return ResourceManager.GetString("ProtocolsTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  SP .
        /// </summary>
        internal static string SP
        {
            get
            {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State
        {
            get
            {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown type .
        /// </summary>
        internal static string UnknownType
        {
            get
            {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable
        {
            get
            {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionTxt
        {
            get
            {
                return ResourceManager.GetString("VersionTxt", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Baud Rate:.
        /// </summary>
        internal static string BaudRateTxt
        {
            get
            {
                return ResourceManager.GetString("BaudRateTxt", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Data Bits:.
        /// </summary>
        internal static string DataBitsTxt
        {
            get
            {
                return ResourceManager.GetString("DataBitsTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eop:.
        /// </summary>
        internal static string EopTxt
        {
            get
            {
                return ResourceManager.GetString("EopTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Flow Control:.
        /// </summary>
        internal static string FlowControlTxt
        {
            get
            {
                return ResourceManager.GetString("FlowControlTxt", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Parity:.
        /// </summary>
        internal static string ParityTxt
        {
            get
            {
                return ResourceManager.GetString("ParityTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port Name:.
        /// </summary>
        internal static string PortNameTxt
        {
            get
            {
                return ResourceManager.GetString("PortNameTxt", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Stop Bits:.
        /// </summary>
        internal static string StopBitsTxt
        {
            get
            {
                return ResourceManager.GetString("StopBitsTxt", resourceCulture);
            }
        }






    }
}
